name: greetings-release

on:
  push:
    tags:
      - "greetings-v[0-9]+.[0-9]+.[0-9]" # Push events to matching v*, i.e. greetings-v1.0
      - "greetings-v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. greetings-v1.0-rc1

jobs:
  release-greetings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb
      - name: Set Env Variables
        run: echo "PKG_NAME=greetings" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/greetings-')
      - name: Test Greetings
        run: cd pkg/${{env.PKG_NAME}} && go test
      - name: Build Greetings
        run: cd pkg/hello && go build
      - name: Generate Archive
        run: tar cfvz ${{env.PKG_NAME}}.tar.gz pkg/**
      - name: Release Greetings
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{env.PKG_NAME}}.tar.gz
            pkg/hello/hello
