name: greetings-release

on:
  push:
    tags:
      - "greetings-v[0-9]+.[0-9]+.[0-9]" # Push events to matching v*, i.e. greetings-v1.0
      - "greetings-v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. greetings-v1.0-rc1

jobs:
  release-gauntlet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Greetings
        run: cd $GITHUB_WORKSPACE/pkg/greetings && go test
      - name: Build and Release Greetings
        uses: softprops/action-gh-release@v1
        run: cd $GITHUB_WORKSPACE/pkg/hello && go build
        with:
          files: |
            $GITHUB_WORKSPACE/pkg/hello/hello
