name: greetings-release

on:
  push:
    tags:
      - "greetings-go-v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "greetings-go-v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5

jobs:
  release-greetings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb
      - name: Test Greetings
        run: cd pkg/greetings && go test
      - name: Build Greetings
        run: cd pkg/hello && go build
      - name: Generate Archive
        run: tar cfvz greetings.tar.gz pkg/**
      - name: Release Greetings
        uses: softprops/action-gh-release@v1
        with:
          files: |
            greetings.tar.gz
            pkg/hello/hello
