name: ts-tool-release

on:
  push:
    - "ts-tool-v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
    - "ts-tool-v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5

jobs:
  release-ts-tool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb
      - name: Test Tool
        run: cd ts-tool && yarn test
      - name: Generate Archive
        run: tar cfvz ts-tool.tar.gz ts-tool/**
      - name: Release Tool
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ts-tool.tar.gz
